---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  browser: true


extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: off
  no-unused-vars: off
  no-alert: off
  no-undef: off
  quotes: off
  import/extensions: off
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]