name: lint-check
on:
  push:
    branches:
      - '**'
      jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    -name: checks by linter
     run: make make-lint

